from django import forms

class RecommendationForm(forms.Form):
    cuisine_choices = [
        ('Indian', 'Indian'),
        ('North Indian Recipes', 'North Indian Recipes'),
        ('South Indian Recipes', 'South Indian Recipes'),
        ('Bengali Recipes', 'Bengali Recipes'),
        ('Kerala Recipes', 'Kerala Recipes'),
        ('Tamil Nadu', 'Tamil Nadu'),
        ('Maharashtrian Recipes', 'Maharashtrian Recipes'),
        ('Karnataka', 'Karnataka'),
        ('Gujarati Recipes', 'Gujarati Recipes'),
        ('Andhra', 'Andhra'),
        ('Rajasthani', 'Rajasthani'),
        ('Goan Recipes', 'Goan Recipes'),
        ('Punjabi', 'Punjabi'),
        ('Chettinad', 'Chettinad'),
        ('Kashmiri', 'Kashmiri'),
        ('Mangalorean', 'Mangalorean'),
        ('Awadhi', 'Awadhi'),
        ('Parsi Recipes', 'Parsi Recipes'),
        ('Hyderabadi', 'Hyderabadi'),
        ('Konkan', 'Konkan'),
        ('Oriya Recipes', 'Oriya Recipes'),
        ('Mughlai', 'Mughlai'),
        ('Sindhi', 'Sindhi'),
        ('Assamese', 'Assamese'),
        ('Bihari', 'Bihari'),
        ('North East India Recipes', 'North East India Recipes'),
        ('Himachal', 'Himachal'),
        ('Fusion', 'Fusion'),
        ('North Karnataka', 'North Karnataka'),
        ('Coorg', 'Coorg'),
        ('Coastal Karnataka', 'Coastal Karnataka'),
        ('Udupi', 'Udupi'),
        ('Uttar Pradesh', 'Uttar Pradesh'),
        ('Malabar', 'Malabar'),
        ('Pakistani', 'Pakistani'),
        ('South Karnataka', 'South Karnataka'),
        ('Asian', 'Asian'),
        ('Malvani', 'Malvani'),
        ('Lucknowi', 'Lucknowi'),
        ('Sri Lankan', 'Sri Lankan'),
        ('Middle Eastern', 'Middle Eastern'),
        ('Indo Chinese', 'Indo Chinese'),
        ('Nagaland', 'Nagaland'),
        ('Nepalese', 'Nepalese'),
        ('Continental', 'Continental'),
        ('Uttarakhand-North Kumaon', 'Uttarakhand-North Kumaon'),
        ('Haryana', 'Haryana'),
        ('Kongunadu', 'Kongunadu'),
        ('Jharkhand', 'Jharkhand'),
        ('Chinese', 'Chinese'),
        ('Sichuan', 'Sichuan'),
        ('Thai', 'Thai'),
        ('Arab', 'Arab'),
        ('Afghan', 'Afghan'),
        ('African', 'African'),
        ('Korean', 'Korean'),
    ]
    cuisine = forms.ChoiceField(choices=cuisine_choices)

    course_choices = [
        ('Lunch', 'Lunch'),
        ('Side Dish', 'Side Dish'),
        ('Dinner', 'Dinner'),
        ('Dessert', 'Dessert'),
        ('South Indian Breakfast', 'South Indian Breakfast'),
        ('Main Course', 'Main Course'),
        ('North Indian Breakfast', 'North Indian Breakfast'),
        ('Appetizer', 'Appetizer'),
        ('Indian Breakfast', 'Indian Breakfast'),
        ('Snack', 'Snack'),
        ('One Pot Dish', 'One Pot Dish'),
        ('World Breakfast', 'World Breakfast'),
        ('Brunch', 'Brunch'),
    ]
    course = forms.ChoiceField(choices=course_choices)

    diet_choices = [
        ('Vegetarian', 'Vegetarian'),
        ('High Protein Vegetarian', 'High Protein Vegetarian'),
        ('Diabetic Friendly', 'Diabetic Friendly'),
        ('Non Vegeterian', 'Non Vegeterian'),
        ('High Protein Non Vegetarian', 'High Protein Non Vegetarian'),
        ('Eggetarian', 'Eggetarian'),
        ('No Onion No Garlic (Sattvic)', 'No Onion No Garlic (Sattvic)'),
        ('Gluten Free', 'Gluten Free'),
        ('Vegan', 'Vegan'),
    ]
    diet = forms.ChoiceField(choices=diet_choices)

    ingredients = forms.CharField(widget=forms.Textarea)
