# Generated by Django 5.0 on 2024-04-03 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('cuisine', models.CharField(max_length=50)),
                ('diet', models.CharField(max_length=50)),
                ('course', models.CharField(max_length=50)),
                ('prep_time', models.CharField(blank=True, max_length=50, null=True)),
                ('ingredients', models.TextField()),
                ('instructions', models.TextField()),
                ('full_text', models.TextField()),
            ],
        ),
    ]
